name: how_wet_will_i_get
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.3.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
    assets:
    - assets/images/rain-none.png
    - assets/images/rain-licht.png
    - assets/images/rain-normal.png
    - assets/images/rain-hard.png
    - assets/images/check.png
    - assets/images/hoodie.png
    - assets/images/protection.png
    - assets/images/raincoat.png
    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins.ttf
